* Bookmarks
** What is this about?

   When I find an interesting article or video, I share it here. Most
   of these are possible starting points for a short presentation, or
   may be useful for your application research.

   I usually look at the articles in some detail (though I rarely work
   through them - that would be your job), and assign a label for the
   difficulty level Lvl = 0 (simple), 1 (moderate), 2 (difficult), or 3
   (hard).

   Papers can be hard for different reason: length, technical
   vocabulary, writing style, mathematics, number of citations etc. If
   you find any of these interesting and want to use them for your
   research, you might ask me why I assigned a particular level.

** Computational complexity of a single neuron (Lvl=0)

   Whitten A (Sept 2, 2021). How Computationally Complex Is a Single
   Neuron? [[https://www.quantamagazine.org/how-computationally-complex-is-a-single-neuron-20210902/][Online: Quanta Magazine.]]

   #+begin_quote
   Computational neuroscientists taught an artificial neural network
   to imitate a biological neuron. The result offers a new way to
   think about the complexity of single brain cell. [...] The language
   of artificial neural networks may provide new insight into the
   power of neurons and, ultimately, the brain. “Thinking in terms of
   layers and depths and widths gives us an intuitive sense of
   computational complexity,” said Grace Lindsay, a computational
   neuroscientist at University College London. Yet Lindsay also
   cautions that the new work is still only comparing a model to a
   model. Unfortunately, it’s currently impossible for neuroscientists
   to record the full input-output function of a real neuron, so
   there’s likely more going on that the model of a biological neuron
   isn’t capturing. In other words, real neurons might be even more
   complex.
   #+end_quote

   With regard to modeling, the remark that this work "is still only
   comparing a model to a model" is very interesting, I thought. This
   does mean that neuroscience is not really an empirical science -
   its models are not simulating reality, but only modelled reality.
