#+TITLE:DSC 482.01 Fall 2021 Syllabus
#+AUTHOR: Marcus Birkenkrahe
#+SUBTITLE: Data Modeling
#+options: toc:nil
* General Course Information

  * Meeting Times: Tuesday & Thursday, 14:30-15:45 hrs
  * Meeting place: Derby 209
  * Professor: Marcus Birkenkrahe
  * Office: Derby 210
  * Phone: (870) 307-7254
  * Office hours: Mon/Wed/Fri 10:00-10:30 AM; Tue/Thu 4-4:30 PM
  * Text: /Model Thinking: What You Need To Make Data Work For You/,
    by Scott E. Page, Reprint edition, Basic Books (March 16,
    2021). ([[https://www.amazon.com/Model-Thinker-What-Need-Know/dp/1541675711/][Amazon]])

** Objectives

   Models are abstractions that explain parts of the real world,
   e.g. to address, if not solve, complex problems like climate
   change, pandemics, or space exploration. Since the real world is
   only accessible to us through observation, observable data are key
   to building, verifying and using models. To support
   decision-making, data and processes are mined and modeled. In this
   course, we will explore model thinking and a wide array of data and
   process modeling tools. This special topic seminar is for everyone
   who is interested in using models and modeling languages to better
   understand the challenges and achievements of modeling.

** Student Learning Outcomes

   Students who complete DSC 482.02 are able to:

   * Understand data and process modeling challenges
   * Use a variety of modeling languages to create models
   * Make use of different modeling software environments
   * Understand, and can present current modeling research
   * Apply modeling tools to an area of their knowledge
   * Write a scientific (IMRaD) essay on modern modeling methods

** Course requirements

   No prior knowledge required. Experience and knowledge of data or
   process modeling methods (e.g. Entity Relationship Diagrams, or
   Unified Modeling Language) is useful but not critical. Curiosity
   and active participations, especially during classroom
   presentations and discussion, is important. You will gain advanced
   data and process literacy skills by taking this course.

** Grading system

   | WHEN       | DESCRIPTION   | IMPACT |
   |------------+---------------+--------+
   | TBD        | Final exam    |    40% |
   | Last week  | Final essay   |    30% |
   | Weekly lab | Practice      |    15% |
   | Weekly lab | Participation |    15% |

*** Grading table

    This table is used to convert completion rates into letter
    grades. For the midterm results, letter grades still carry signs,
    while for the term results, only straight letters are given (by
    rounding up).

    |--------+-----------------+---------------|
    |    %   | MIDTERM GRADE   | FINAL GRADE   |
    |--------+-----------------+---------------|
    | 100-98 | A+              |               |
    |  97-96 | A               | A             |
    |  95-90 | A-              |               |
    |--------+-----------------+---------------|
    |  89-86 | B+              |               |
    |  85-80 | B               | B             |
    |  79-76 | B-              |               |
    |--------+-----------------+---------------|
    |  75-70 | C+              |               |
    |  69-66 | C               | C             |
    |  65-60 | C-              |               |
    |--------+-----------------+---------------|
    |  59-56 | D+              |               |
    |  55-50 | D               | D             |
    |--------+-----------------+---------------|
    |   49-0 | F               | F             |
    |--------+-----------------+---------------|

*** Final exam (30%)

    * Complete multiple choice questions
    * Question examples at the start of a new week
    * Open book exam, 120 minutes

*** Final essay (40%)

    * Review a book based on a model or method, OR
    * Review an research article based on a model or method, OR
    * Apply model(s) or method(s) to an area of your knowledge
    * Essay length: 15-20 pages (5,000-8,000 words)

*** Weekly practice (15%)

    * Create a glossary of technical terms & present, AND
    * Connect session content to personal domain knowledge, AND
    * Complete set lab exercises in class

*** Weekly participation (15%)

    * Participate in group discussions, OR
    * Participate in class discussion, OR
    * Present a glossary term, OR
    * Present a personal model application

** Grading examples

*** Example - Midterm grade

    At midterms, student X has achieved the following results:

    | GRADE PART           | WEIGHT   | RESULT   |
    |----------------------+----------+----------|
    | Weekly practice      |      15% |      80% |
    | Weekly participation |      15% |      90% |

    # Student X's midterm result is computed as follows:

    # #+begin_src R :session :results output
    #   ## midterm weights (only practice and participation)
    #   weight_m <- c("practice"=0.5,
    #                 "participation"=0.5)
    #   ## results vector
    #   result_m <- c("practice"=80,
    #                 "participation"=90)
    #   ## midterm grade
    #   grade_m <-
    #     weight_m["practice"] * result_m["practice"] +
    #     weight_m["participation"] * result_m["participation"]
    #   names(grade_m) <- NULL
    #   grade_m
    # #+end_src

    # #+RESULTS:
    # : [1] 85

    Student X's midterm result is a "B" (~85%~).

*** Example - Final grade

    After the finals, student X has achieved the following results:

    | GRADE PART           | WEIGHT   | RESULT   |
    |----------------------+----------+----------|
    | Final exam           |      30% |      95% |
    | Final essay          |      40% |      95% |
    | Weekly practice      |      15% |      80% |
    | Weekly participation |      15% |      90% |

    # Student X's midterm result is computed as follows:

    # #+begin_src R :session :results output
    #   ## full term weight vector according to grading table
    #   weight <- c("exam"= 0.3,
    #               "essay"=0.4,
    #               "practice"=0.15,
    #               "participation"=0.15)
    #   ## results vector
    #   result <- c("exam"=95,
    #               "essay"=95,
    #               "practice"=80,
    #               "participation"=90)
    #   ## midterm grade
    #   grade <-
    #     weight["exam"] * result["exam"] +
    #     weight["essay"] * result["essay"] +
    #     weight["practice"] * result["practice"] +
    #     weight["participation"] * result["participation"]
    #   names(grade) <- NULL
    #   grade
    # #+end_src

    # #+RESULTS:
    # : [1] 92

    Student X's midterm result is an "A" (~92%~).

  
* Standard Policies
** Honor Code

   All graded work in this class is to be pledged in accordance with
   the Lyon College Honor Code. The use of a phone for any reason
   during the course of an exam is considered an honor code
   violation.

** Class Attendance Policy

   Students are expected to attend all class periods for the courses
   in which they are enrolled. They are responsible for conferring
   with individual professors regarding any missed
   assignments. Faculty members are to notify the Registrar when a
   student misses the equivalent of one, two, three, and four weeks
   of class periods in a single course. Under this policy, there is
   no distinction between “excused” and “unexcused” absences, except
   that a student may make up work missed during an excused
   absence. A reminder of the college’s attendance policy will be
   issued to the student at one week, a second reminder at two weeks,
   a warning at three weeks, and notification of administrative
   withdrawal and the assigning of an “F” grade at four
   weeks. Students who are administratively withdrawn from more than
   one course will be placed on probation or suspended.

** Disabilities

   Students seeking reasonable accommodations based on documented
   learning disabilities must contact Danell Hetrick in the Morrow
   Academic Center at (870) 307-7021 or at danell.hetrick@lyon.edu.

** Harassment, Discrimination, and Sexual Misconduct

   Title IX and Lyon’s policy prohibit harassment, discrimination and
   sexual misconduct. Lyon encourages anyone experiencing harassment,
   discrimination or sexual misconduct to talk to Lai-Monte Hunter,
   Title IX Coordinator and Vice-President for Student Life, or
   Sh’Nita Mitchell, Title IX Investigator and Associate Dean for
   Residence Life, about what happened so they can get the support
   they need and Lyon can respond appropriately.  Lyon is legally
   obligated to respond to reports of sexual misconduct, and
   therefore we cannot guarantee the confidentiality of a report,
   unless made to a confidential resource (Chaplain, Counselor, or
   Nurse). As a faculty member, I am required to report possible
   Title IX violations and must provide our Title IX coordinator with
   all relevant details.  I cannot, therefore, guarantee
   confidentiality.

** College-Wide COVID-19 Policies for Fall, 2021

   Masks are mandated for all students in classrooms, laboratories and studios.  They remain optional for all persons on the Lyon campus in all other locations and outside.
   Participation in community surveillance testing in mandatory.
   Vaccines are STRONGLY encouraged for all faculty, staff, and students. Vaccines are NOT MANDATED for Lyon College community members.

   Details specific to this course may be found in the subsequent pages of this syllabus. Those details will include at least the following:
   A description of the course consistent with the Lyon College catalog.
   A list of student learning outcomes for the course.
   A summary of all course requirements.
   An explanation of the grading system to be used in the course.
   Any course-specific attendance policies that go beyond the College policy.
   Details about what constitutes acceptable and unacceptable student collaboration on graded work.

* Course specific information
** Assignments and Honor Code

   There will be numerous assignments during the semester -
   programming, lessons, tests, and sprint reviews. They are due at
   the beginning of the class period on the due date. Once class
   begins, the assigment will be considered one day late if it has not
   been turned in.  Late programs will not be accepted without an
   extension.  Extensions will *not* be granted for reasons such as:

   * You could not get to a computer
   * You could not get a computer to do what you wanted it to do
   * The network was down
   * The printer was out of paper or toner
   * You erased your files, lost your homework, or misplaced your
     flash drive
   * You had other coursework or family commitments that interfered
     with your work in this course

   Put “Pledged” and a note of any collaboration in the comments of
   any program you turn in. Programming assignments are individual
   efforts, but you may seek assistance from another student or the
   course instructor.  You may not copy someone else’s solution. If
   you are having trouble finishing an assignment, it is far better to
   do your own work and receive a low score than to go through an
   honor trial and suffer the penalties that may be involved.

   What is cheating on an assignment? Here are a few examples:

   * Having someone else write your assignment, in whole or in part
   * Copying an assignment someone else wrote, in whole or in part
   * Collaborating with someone else to the extent that your
     submissions are identifiably very similar, in whole or in part
   * Turning in a submission with the wrong name on it

   What is not cheating?  Here are some examples:

   * Talking to someone in general terms about concepts involved in
     an assignment
   * Asking someone for help with a specific error message or bug in
     your program
   * Getting help with the specifics of language syntax or citation
     style
   * Utilizing information given to you by the instructor

   Any assistance must be clearly explained in the comments at the
   beginning of your submission.  If you have any questions about
   this, please ask or review the policies relating to the Honor Code.

   Absences on Days of Exams:

   Test “make-ups” will only be allowed if arrangements have been
   made prior to the scheduled time.  If you are sick the day of the
   test, please e-mail me or leave a message on my phone before the
   scheduled time, and we can make arrangements when you return.

** Important Dates:

   | DATE           | DESCRIPTION                                |
   |----------------+--------------------------------------------|
   | August 30      | Last day to drop w/o record of a course    |
   | September 6    | Labor day (no classes)                     |
   | October 2-5    | Fall break (no classes)                    |
   | October 6      | Mid-semester grade reports due             |
   | October 13     | Last day to drop a course with a "W" grade |
   | October 20     | Service day on campus (no classes)         |
   | Nobember 24-28 | Thanksgiving Break (no classes)            |
   | December 3     | Last day of class                          |
   | December 6-10  | Final exams                                |
   | December 15    | Final grades due                           |

** Schedule and session content

   * Mini lectures on given topics are followed by discussion
   * Lab sessions involve in-class exercises and challenges
   * There's a short test at the beginning of every week
   * There's not one text book for all class topics
   * Bring articles, models, applications to class for discussion

   | DATE   | LECTURES/GLOSSARY/LABS              |
   |--------+-------------------------------------|
   | 17-Aug | Course overview & purpose           |
   | 19-Aug | Many-model thinking (lab)           |
   | 24-Aug | Why model?                          |
   | 26-Aug | Why model? (lab)                    |
   | 31-Aug | Many-model science                  |
   | 2-Sep  | Many-model science (lab)            |
   | 7-Sep  | Modeling human actors               |
   | 9-Sep  | Modeling human actors (lab)         |
   | 14-Sep | Process management & EPCs           |
   | 16-Sep | Process management & EPCs (lab)     |
   | 21-Sep | Business Process Model and Notation |
   | 23-Sep | BPMN (lab)                          |
   | 28-Sep | Performance management & Analytics  |
   | 30-Sep | PM & Analytics (lab)                |
   | 7-Oct  | Distribution models (lab)           |
   | 12-Oct | Linear models                       |
   | 14-Oct | Linear models (lab)                 |
   | 19-Oct | Agile management                    |
   | 21-Oct | Agile management (lab)              |
   | 26-Oct | Models of value and power           |
   | 28-Oct | Models of value and power (lab)     |
   | 2-Nov  | Unified Modeling Language (UML)     |
   | 4-Nov  | UML (lab)                           |
   | 9-Nov  | Robotic process automation (RPA)    |
   | 11-Nov | RPA (lab)                           |
   | 16-Nov | Non-linear models                   |
   | 18-Nov | Non-linear models (lab)             |
   | 23-Nov | Process mining                      |
   | 30-Nov | COVID-19 models                     |
   | 2-Dec  | Summary and outlook                 |
