#+options: toc:nil
* FINAL ESSAY

  Dear course participants -

  These are the instructions[fn:1] for handing in the final essay
  material. Please read them carefully, follow them to the letter and
  contact me immediately if there are issues or mistakes[fn:2]. Submit
  earlier, not in the last minute, to be on the safe side!

  The deadline for submitting the presentation is *Friday, December 3,
  12AM CST* (midnight in Batesville).

  1) *Fill in and sign* [[https://github.com/birkenkrahe/org/blob/master/Honor_pledge.pdf][this honor sheet (PDF)]] and write
     *"pledged"* next to your name in the column "Honor Pledge".

  2) Upload your *essay document* and the *scan of the
     signed honor sheet* [[https://github.com/birkenkrahe/ai482/tree/main/presentations/4th_sprint_review][to this GitHub folder]] - please add your
     name(s) to the title of the file. Remember 

  3) Post the *link* to your video presentation [[https://github.com/birkenkrahe/ai482/discussions][to the discussion
     forum]] in GitHub[fn:3]. Test the link before posting it!

  4) When you're done, *send me an email* (birkenkrahe@lyon.edu)
     confirming that you've done all of this, including which
     course you're in.

  5) Await my formative (comments) and summative (grade) feedback
     (via email) based on [[https://github.com/birkenkrahe/org/blob/master/Presentation_Assessment_Form.pdf][this presentation assessment form]] (PDF).

     Cheers, and have a good Thanksgiving break & a successful exam period!
  Marcus Birkenkrahe

* Footnotes

[fn:1] This text is available as: Update in Schoology, Email to
participants, course FAQ in GitHub.

[fn:2]Please be advised that I'm traveling in Europe between November
29 and December 15 (communication of final grades), and will not be
easily reachable.
