#+TITLE:Robotic Process Automation
#+AUTHOR:Marcus Birkenkrahe
#+SUBTITLE: Data modeling seminar 482.02 Fall 2021
#+STARTUP: overview
#+OPTIONS: toc:1 num:nil ^:nil
#+INFOJS_OPT: :view:info
* What will you learn?

  * What is Robotic Process Automation?
  * How is it done in practice?

* What is RPA

  * "[[https://youtu.be/aZDaNVh3l0k][What is Robotic process automation?]]" 7 min (IBM, 2021)

** Summary

   1) Automate repeated, tedious tasks
   2) E.g. Optical Character Recognition (OCR) for data extraction
   3) "Intelligent" tools / machine learning (model building)
   4) Low code / no code
   5) Concurrency
   6) RPA as a Service (plug-and-play)
   7) Collaboration potential
   
** There is (much) more

   * Dependencies are crucial
   * More common: workflow integration
   * Create agents through app combination
   * Combine with process modeling (BPMN)
   * Vendors: SAP Signavio, Integromat/Celonis, [[https://www.uipath.com/][UIPath]], [[https://ifttt.com/][IFTTT]]
   * No-code focus: bubble, SAP AppGyver

* How is it done in practice?

  * Signavio demonstration ([[rpa][Signavio, 2021]])
  * Integromat example ([[int][Integromat, 2016]])

** Signavio Workflow Accelerator

   * Works in concert with BPMN process modeling
   * Do it yourself in editor.signavio.com (enterprise license)

** Integromat

   * Automated workflow with defined APIs
   * Do it yourself (free) at integromat.com

** Bubble / AppGyver

   I'm not a friend of low code/no code approaches - for a bunch of
   reasons. However, many developers (of web apps) seem to think
   differently, or perhaps it's just clever marketing. No matter:
   ~bubble.io~ seems like a good place to look at some use cases.

   Here is a [[https://bubble.io/showcase][gallery of no-code apps built with Bubble]].

   AppGyver was recently acquired by SAP (like Signavio) - the
   Composer Pro platform is free. [[https://docs.appgyver.com/appgyver-academy][Here is some onboarding help.]]

   I have no used either of these platforms yet but I'd like to
   contrast coding and no-coding programs and projects for a future
   research and/or teaching project.
   
* References

  IBM Technology (Mar 19, 2021). What is RPA (Robotic Process
  Automation)? [video] [[https://youtu.be/aZDaNVh3l0k][URL: youtu.be/aZDaNVh3l0k]]

  <<rpa>> SAP Signavio Process Governance (2021) [website]. URL:
  [[https://www.signavio.com/products/process-governance/][signavio.com/products/process-governance/]]

  <<int>> Integromat (Aug 11, 2016). What is Integromat? [video]. [[https://youtu.be/61HQ_DWoFr8][URL:
  youtu.be/61HQ_DWoFr8]]
